Add Haskell support
npezza93/ttags pull request #11
Opened 2023-09-24 13:09 UTC by mrcjkb

2023-09-26 16:47 UTC, mrcjkb commented on src/haskell.rs
> +use npezza93_tree_sitter_tags::{Tag as TSTag, TagsContext, TagsConfiguration};
Note: this file is almost identical to `src/rust.rs`.
It might make sense to extract `generate_tags` into a strategy.

2023-09-27 18:10 UTC, npezza93 commented
Sweet, ill check it out later today!

2023-09-28 23:59 UTC, npezza93 requested changes

2023-09-28 23:59 UTC, npezza93 commented on src/tagger.rs
> +        let haskell_config                       = haskell::config();
Looks like some weird spacing here. Mind making it match the line above?

2023-09-29 01:56 UTC, merged